### ISSUE TITLE
Course 3 and Course 4

### ISSUE THREAD

**Issue by RamanHacks** [joelowj/Machine-Learning-and-Reinforcement-Learning-in-Finance#6]
When are the assignments of the remaining courses (course 3 and 4) going to be uploaded?

**Comment by joelowj** [comment]
Hi @RamanHacks,

For course 3's assignment, the grader is having a great ton of issues with their grader. I will check once a while to see if they have update the assignment's grader and if I manage to clear most of them. I will upload those assignments. The reason for doing this is also because I do not want to mislead people into thinking that it is the grader issue while in fact it could be a mistake on my part. 

As for course 4, majority of the assignment are quizzes. I am a bit reluctant to upload them since one can give it a few attempts to clear it. The reason I started the repository is because the assignment instructions are extremely vague and hopefully I can get people to discuss their ideas or debate about their approach on the issues thread here. Having say that, if there is indeed a demand for course 4 quizzes, I will upload them shortly.

Let's just give this great people who put the course together some time to clear out the bugs in the grader. I will also be having my exams in the next 2 weeks. Afterwards, I will update this repository thoroughly  from course 1 to 4. In the mean time, if you have any doubts or questions regarding to the assignment. Feel free to start a discussion on another thread.
